"""Add UserApiKey model

Revision ID: a861a936874c
Revises: 
Create Date: 2025-11-29 18:38:46.835004

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'a861a936874c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
