import React, { useEffect, useState, useRef } from "react"; // Added useRef
import ReactMarkdown from "react-markdown";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { vscDarkPlus } from "react-syntax-highlighter/dist/esm/styles/prism";
import rehypeSlug from "rehype-slug";
import { GeneratedDoc } from "../types";
import { Copy, Check, Download, List, FileText } from "lucide-react"; // FileText added for empty state

interface DocViewerProps {
  doc: GeneratedDoc | null;
  isLoading: boolean;
}

interface TocItem {
  level: number;
  text: string;
  id: string;
}

const DocViewer: React.FC<DocViewerProps> = ({ doc, isLoading }) => {
  const [copied, setCopied] = useState(false);
  const [toc, setToc] = useState<TocItem[]>([]);
  const contentRef = useRef<HTMLDivElement>(null); // Ref for scrolling

  useEffect(() => {
    if (doc?.markdown) {
      const headings: TocItem[] = [];
      const lines = doc.markdown.split("\n");
      const slugify = (text: string) =>
        text
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, "-")
          .replace(/(^-|-$)+/g, "");

      lines.forEach((line) => {
        // Only consider H1, H2, H3 for TOC for brevity
        const match = line.match(/^(#{1,3})\s+(.+)$/);
        if (match) {
          const rawText = match[2];
          // Skip headings that contain inline code (backticks)
          if (rawText.includes('`')) {
            return;
          }
          
          headings.push({
            level: match[1].length,
            text: rawText,
            id: slugify(rawText), // Use raw text for ID slugification to match rehypeSlug
          });
        }
      });
      setToc(headings);

      // Scroll to top when doc changes
      if (contentRef.current) {
        contentRef.current.scrollTop = 0;
      }

    } else {
      setToc([]);
    }
  }, [doc]);

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };


  const handleDownload = () => {
    if (doc) {
      const blob = new Blob([doc.markdown], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${doc.id}.md`; // Use ID as filename
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url); // Clean up the URL object
    }
  };

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-400 animate-pulse bg-white">
        <div className="w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mb-4"></div>
        <p>Generating AI Documentation...</p>
        <p className="text-xs mt-2 opacity-70">Consulting Gemini Models</p>
      </div>
    );
  }

  if (!doc) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-400 bg-slate-50">
        <div className="p-6 bg-white rounded-2xl shadow-sm border border-slate-200 flex flex-col items-center">
           <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mb-4">
             <FileText size={32} className="text-slate-300" />
           </div>
           <p className="font-medium text-slate-600">Select a document to view</p>
           <p className="text-sm text-slate-400 mt-1">Choose from the sidebar to start</p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col bg-white">
      {/* Header */}
      <div className="border-b border-slate-200 px-8 py-4 flex justify-between items-center bg-white sticky top-0 z-20 shadow-sm">
        <div className="flex items-center gap-3">
             <div className="p-2 bg-blue-50 text-blue-600 rounded-lg">
                <List size={20} />
             </div>
             <div>
                <h2 className="text-lg font-bold text-slate-800 leading-tight">{doc.id}</h2>
                <p className="text-xs text-slate-400">Generated by DocGen AI</p>
             </div>
        </div>
        
        <div className="flex gap-2">
          <button
            onClick={() => handleCopy(doc.markdown)}
            className="flex items-center gap-2 px-3 py-1.5 text-slate-500 hover:text-blue-600 hover:bg-blue-50 transition-all rounded-md border border-slate-200 text-sm font-medium"
            title="Copy Markdown"
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            <span>{copied ? "Copied" : "Copy"}</span>
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-3 py-1.5 text-slate-500 hover:text-blue-600 hover:bg-blue-50 transition-all rounded-md border border-slate-200 text-sm font-medium"
            title="Download Markdown"
          >
            <Download size={14} />
            <span>Download</span>
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-hidden flex">
        {/* Main Content */}
        <div ref={contentRef} className="flex-1 overflow-y-auto px-12 py-8 scroll-smooth">
          <div className="max-w-4xl mx-auto prose prose-slate prose-headings:scroll-mt-20 prose-pre:p-0 prose-pre:bg-transparent">
            <ReactMarkdown
              rehypePlugins={[rehypeSlug]}
              components={{
                code({ node, inline, className, children, ...props }: any) {
                  const match = /language-(\w+)/.exec(className || "");
                  const language = match ? match[1] : "clike"; // Default to clike if no language specified
                  return !inline && match ? (
                    <div className="relative group my-6 rounded-xl overflow-hidden border border-slate-200 shadow-sm">
                      <div className="bg-slate-100 px-4 py-2 text-xs text-slate-500 border-b border-slate-200 flex justify-between items-center font-mono">
                         <span>{language}</span>
                         <button 
                           onClick={() => handleCopy(String(children).replace(/\n$/, ""))}
                           className="hover:text-blue-600 transition-colors"
                         >
                            <Copy size={12}/>
                         </button>
                      </div>
                      <SyntaxHighlighter
                        {...props}
                        style={{
                          ...vscDarkPlus,
                          'code[class*="language-"]': { ...vscDarkPlus['code[class*="language-"]'], background: '#1e1e1e' },
                          'pre[class*="language-"]': { ...vscDarkPlus['pre[class*="language-"]'], background: '#1e1e1e' },
                          'attr-name': { color: '#ce9178' }, // Orange for attributes
                          'function': { color: '#dcdcaa' }, // Yellow for functions
                          'keyword': { color: '#c586c0' }, // Purple for keywords
                          'tag': { color: '#569cd6' },      // Blue for tags
                          'selector': { color: '#d7ba7d' }, // Gold for selectors
                          'string': { color: '#ce9178' },    // Orange for strings (re-apply from attr-name if it gets red)
                          'comment': { color: '#6a9955' },   // Green for comments
                          'operator': { color: '#d4d4d4' },
                        }}
                        language={language}
                        PreTag="div" // Use div instead of pre to avoid nesting issues with the wrapper
                        customStyle={{ margin: 0, borderRadius: 0, padding: '1rem' }}
                      >
                        {String(children).replace(/\n$/, "")}
                      </SyntaxHighlighter>
                    </div>
                  ) : (
                    <code
                      className="bg-slate-100 text-indigo-500 px-1.5 py-0.5 rounded-md text-sm font-mono border border-slate-200"
                      {...props}
                    >
                      {children}
                    </code>
                  );
                },
                h1: ({node, ...props}) => <h1 className="text-3xl font-extrabold text-slate-900 mb-6 pb-2 border-b border-slate-100" {...props} />,
                h2: ({node, ...props}) => <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4" {...props} />,
                h3: ({node, ...props}) => <h3 className="text-xl font-semibold text-slate-700 mt-8 mb-3" {...props} />,
              }}
            >
              {doc.markdown}
            </ReactMarkdown>
          </div>
        </div>

        {/* Table of Contents (Right Sidebar) */}
        {toc.length > 0 && (
          <div className="w-48 border-l border-slate-200 bg-slate-50/50 overflow-y-auto hidden xl:block p-6">
            <div className="sticky top-0">
              <h4 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4">
                On this page
              </h4>
              <nav className="space-y-1">
                {toc.map((item, index) => (
                  <a
                    key={index}
                    href={`#${item.id}`}
                    className={`
                      block text-sm py-1 transition-colors hover:text-blue-600
                      ${item.level === 1 ? "font-semibold text-slate-700" : "text-slate-500"}
                      ${item.level === 2 ? "pl-3" : ""}
                      ${item.level === 3 ? "pl-6" : ""}
                    `}
                  >
                    {item.text}
                  </a>
                ))}
              </nav>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default DocViewer;
